name: Site
title: Site
options:
  changeTitle: true

tabs:
  pages:
    sections:
      pages:
        headline: Pages
        type: pages
  overview:
    sections:
      details:
        headline: Details
        type: fields
          fields:
