name: Site
title: Site
sections:
    fields:
        headline: details
        type: fields
        fields:
            header:
                type: text
            acknowledgement:
                type: textarea
    pages:
        headline: Pages
        type: pages
