title: Site

tabs:

  pages:
    preset: pages
    unlisted: true

  details:
    fields:
      headline:
        type: text
      acknowledgement:
        type: textarea
      about:
        type: blocks
        fieldsets:
          - text
