title: Site

columns:

  left:
    width: 1/2
    sections:
      fields:
        fields:
          headline:
            label: Headline Variations
            type: blocks
            fieldsets:
              - text
          acknowledgement:
            type: textarea
          about:
            type: blocks
            fieldsets:
              - text
          team:
            type: blocks
            fieldsets:
              - text
              - heading
          supporters:
            type: blocks
            fieldsets:
              - text
          contributors:
            type: blocks
            fieldsets:
              - text

  right:
    width: 1/2
    sections:
      drafts:
        type: pages
        headline: Drafts
        status: draft
      unlisted:
        type: pages
        headline: Unlisted
        status: unlisted
      published:
        type: pages
        headline: Published pages
        status: listed
